findbulb_new_idea:
    path:   /new
    defaults: { _controller: FindbulbBundle:Idea:new }
    
findbulb_upvote_idea:
    path: /up-vote/{ideaId}
    defaults: { _controller: FindbulbBundle:Idea:upVote }
    
findbulb_downvote_idea:
    path: /down-vote/{ideaId}
    defaults: { _controller: FindbulbBundle:Idea:downVote }
    
findbulb_view_idea:
    path: /view/{ideaId}
    defaults: { _controller: FindbulbBundle:Idea:view }

findbulb_edit_idea:
    path: /edit/{ideaId}
    defaults: { _controller: FindbulbBundle:Idea:edit }
    
findbulb_close_idea:
    path: /close/{ideaId}
    defaults: { _controller: FindbulbBundle:Idea:close }
    
    
    
    
    
    
findbulb_del_comment:
    path: /del-comment/{commentId}
    defaults: { _controller: FindbulbBundle:Idea:delComment }
    
findbulb_add_comment:
    path: /add-comment
    defaults: { _controller: FindbulbBundle:Idea:addComment }